// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package xxxx

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AxxxClient is the client API for Axxx service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AxxxClient interface {
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
}

type axxxClient struct {
	cc grpc.ClientConnInterface
}

func NewAxxxClient(cc grpc.ClientConnInterface) AxxxClient {
	return &axxxClient{cc}
}

func (c *axxxClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/aaaa.xxxx.Axxx/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AxxxServer is the server API for Axxx service.
// All implementations must embed UnimplementedAxxxServer
// for forward compatibility
type AxxxServer interface {
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
	mustEmbedUnimplementedAxxxServer()
}

// UnimplementedAxxxServer must be embedded to have forward compatible implementations.
type UnimplementedAxxxServer struct {
}

func (UnimplementedAxxxServer) SayHello(context.Context, *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedAxxxServer) mustEmbedUnimplementedAxxxServer() {}

// UnsafeAxxxServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AxxxServer will
// result in compilation errors.
type UnsafeAxxxServer interface {
	mustEmbedUnimplementedAxxxServer()
}

func RegisterAxxxServer(s grpc.ServiceRegistrar, srv AxxxServer) {
	s.RegisterService(&Axxx_ServiceDesc, srv)
}

func _Axxx_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AxxxServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aaaa.xxxx.Axxx/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AxxxServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Axxx_ServiceDesc is the grpc.ServiceDesc for Axxx service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Axxx_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aaaa.xxxx.Axxx",
	HandlerType: (*AxxxServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _Axxx_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "Axxx.proto",
}
